server:
  port: 8001

moex:
  bonds:
    corporate:
      url: "https://iss.moex.com/iss/engines/stock/markets/bonds/boards/TQCB/securities.xml?iss.meta=off&iss.only=securities&securities.columns=SECID,PREVPRICE,SHORTNAME"
    government:
      url: "https://iss.moex.com/iss/engines/stock/markets/bonds/boards/TQOB/securities.xml?iss.meta=off&iss.only=securities&securities.columns=SECID,PREVPRICE,SHORTNAME"

logging:
  level:
    org.alexv.moexservice.client : DEBUG

spring:
  cache:
    caffeine:
      spec: maximumSize=48, expireAfterAccess=1h

resilience4j:
  retry:
    instances:
      bond-retry:
        max-attempts: 5
        wait-duration: 2s

  circuitbreaker:
    instances:
      bond-breaker:
        sliding-window-type: count_based
        sliding-window-size: 5
        minimum-number-of-calls: 5
        failure-rate-threshold: 75
        wait-duration-in-open-state: 10s
        automatic-transition-from-open-to-half-open-enabled:
        max-wait-duration-in-half-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 2
